export const EXERCISE_DATA = {
  warmup: {
    videoId: '44ScXWFaVBs',
    timeMinutes: 10,
    thumbnail: 'https://img.youtube.com/vi/44ScXWFaVBs/maxresdefault.jpg',
    title: 'Warm-up: ROKP',
    reps: '10 minutes',
    notes: 'Range of Knee Position (ROKP) - Essential warm-up to prepare your knees for the workout ahead.',
    videoTitle: 'Walking Backwards for Beginners - ROKP Warm-Up',
    videoDescription: 'Perfect beginner-friendly guide for backward walking/ROKP technique',
  },
  step1: {
    videoId: 'gNS_QjGAs_k',
    timeMinutes: 2,
    thumbnail: 'https://img.youtube.com/vi/gNS_QjGAs_k/maxresdefault.jpg',
    title: 'Step 1: Tibialis Raise',
    reps: '25 reps',
    notes: 'No break - Move directly to next exercise',
    videoTitle: 'Tibialis Raise Demonstration',
    videoDescription: 'Proper tibialis raise technique for shin strength',
  },
  step2: {
    videoId: 'BWedccP0o_U',
    timeMinutes: 2,
    thumbnail: 'https://img.youtube.com/vi/BWedccP0o_U/maxresdefault.jpg',
    title: 'Step 2: FHL Calf Raise',
    reps: '25 reps',
    notes: 'No break - Move directly to next exercise',
    videoTitle: 'FHL Calf Raise with Scaling Options',
    videoDescription: 'FHL calf raise technique with single leg progression',
  },
  step2b: {
    videoId: 'gNS_QjGAs_k',
    timeMinutes: 2,
    thumbnail: 'https://img.youtube.com/vi/gNS_QjGAs_k/maxresdefault.jpg',
    title: 'Step 2B: Tibialis Raise (again)',
    reps: '25 reps',
    notes: 'No break - Move directly to next exercise',
    videoTitle: 'Tibialis Raise Demonstration',
    videoDescription: 'Proper tibialis raise technique for shin strength',
  },
  step3: {
    videoId: 'm1aMq9W-jDo',
    timeMinutes: 2,
    thumbnail: 'https://img.youtube.com/vi/m1aMq9W-jDo/maxresdefault.jpg',
    title: 'Step 3: KOT Calf Raise',
    reps: '25 reps',
    notes: 'No break - Move directly to next exercise',
    videoTitle: 'KOT Calf Raise with Scaling Options',
    videoDescription: 'KOT calf raise technique with single leg progression',
  },
  step4: {
    videoId: 'c_VMErzFsZc',
    timeMinutes: 4,
    thumbnail: 'https://img.youtube.com/vi/c_VMErzFsZc/maxresdefault.jpg',
    title: 'Step 4: Patrick Step',
    reps: '25 reps per side',
    notes: '1 set minimum, up to 3 sets per side if weak point - No breaks needed between sets',
    videoTitle: 'Patrick Step-Up Progression',
    videoDescription: 'Patrick > Poliquin > Petersen step-up progression demonstration',
  },
  step5: {
    videoId: 'WQneOolYFbo',
    startTime: 180,
    timeMinutes: 8,
    thumbnail: 'https://img.youtube.com/vi/WQneOolYFbo/maxresdefault.jpg',
    title: 'Step 5: ATG Split Squat',
    reps: '5 sets of 5 reps per side',
    notes: '30 second breaks between each set',
    videoTitle: 'ATG Split Squat Demonstration',
    videoDescription: 'Deep range of motion split squat technique',
  },
  hidden: {
    videoId: 'WQneOolYFbo',
    startTime: 240,
    timeMinutes: 2,
    thumbnail: 'https://img.youtube.com/vi/WQneOolYFbo/maxresdefault.jpg',
    title: 'Hidden Level: VMO Squat',
    reps: '25 reps',
    notes: 'Hidden Level - Focus on VMO activation',
    videoTitle: 'VMO Squat Demonstration',
    videoDescription: 'VMO-focused squat variation for knee strength',
  },
  step6: {
    videoId: 'WQneOolYFbo',
    startTime: 300,
    timeMinutes: 5,
    thumbnail: 'https://img.youtube.com/vi/WQneOolYFbo/maxresdefault.jpg',
    title: 'Step 6: KOT Squat (OPTIONAL)',
    reps: '5 sets of 5 reps',
    notes: 'Optional exercise - Short breaks, no more than 30 seconds per set',
    videoTitle: 'KOT Squat Demonstration',
    videoDescription: 'Full knees-over-toes squat technique',
  },
  step7: {
    videoId: '7IFO7J3AV5Y',
    startTime: 330,
    timeMinutes: 3,
    thumbnail: 'https://img.youtube.com/vi/7IFO7J3AV5Y/maxresdefault.jpg',
    title: 'Step 7: Elephant Walk',
    reps: '36 reps per side',
    notes: '',
    videoTitle: 'Elephant Walk Demonstration',
    videoDescription: 'Elephant walk drill for hamstring and hip mobility',
  },
  step8: {
    videoId: '44ScXWFaVBs',
    timeMinutes: 3,
    thumbnail: 'https://img.youtube.com/vi/44ScXWFaVBs/maxresdefault.jpg',
    title: 'Step 8: L-Sit',
    reps: '60 seconds',
    notes: '1 set minimum, up to 3 sets if weak point - 1-2 minute breaks between sets',
    videoTitle: 'L-Sit Progression Tutorial',
    videoDescription: 'L-sit progression and technique guide',
  },
  step9: {
    videoId: 'Jay0Sd2exg0',
    timeMinutes: 3,
    thumbnail: 'https://img.youtube.com/vi/Jay0Sd2exg0/maxresdefault.jpg',
    title: 'Step 9: Couch Stretch',
    reps: '60 seconds per side',
    notes: '1 set minimum, up to 3 sets if weak point',
    videoTitle: 'Couch Stretch Demonstration',
    videoDescription: 'Proper couch stretch technique for hip flexors',
  },
  step10: {
    videoId: '1fbFMCyRDGs',
    timeMinutes: 6,
    thumbnail: 'https://img.youtube.com/vi/1fbFMCyRDGs/maxresdefault.jpg',
    title: 'Step 10: Piriformis Stretch',
    reps: '2 sets of 90 seconds per side',
    notes: '',
    videoTitle: 'Piriformis Stretch Demonstration',
    videoDescription: 'Piriformis stretch technique for hip and glute mobility',
  },
};

export const EXERCISE_ORDER = [
  'warmup',
  'step1',
  'step2',
  'step2b',
  'step3',
  'step4',
  'step5',
  'hidden',
  'step6',
  'step7',
  'step8',
  'step9',
  'step10',
];
