export const EXERCISE_DATA = {
  warmup: {
    videoId: 'z6A0IXKWUWk',
    timeMinutes: 5,
    thumbnail: 'https://i.ytimg.com/vi/z6A0IXKWUWk/maxresdefault.jpg',
    title: 'Warm-up: ROKP',
    reps: '10 minutes',
    notes: 'Range of Knee Position (ROKP) - Essential warm-up to prepare your knees for the workout ahead.',
    videoTitle: 'Walking Backwards for Beginners - ROKP Warm-Up',
    videoDescription: 'Perfect beginner-friendly guide for backward walking/ROKP technique',
  },
  step1: {
    videoId: 'gNS_QjGAs_k',
    timeMinutes: 1,
    thumbnail: 'https://img.youtube.com/vi/gNS_QjGAs_k/maxresdefault.jpg',
    title: 'Step 1: Tibialis Raise',
    reps: '25 reps',
    notes: 'No break - move directly to next exercise',
    videoTitle: 'Tibialis Raise Demonstration',
    videoDescription: 'Proper tibialis raise technique for shin strength',
  },
  step2: {
    videoId: 'BWedccP0o_U',
    timeMinutes: 1,
    thumbnail: 'https://img.youtube.com/vi/BWedccP0o_U/maxresdefault.jpg',
    title: 'Step 2: FHL Calf Raise',
    reps: '25 reps',
    notes: 'No break - move directly to next exercise',
    videoTitle: 'FHL Calf Raise with Scaling Options',
    videoDescription: 'FHL calf raise technique with single leg progression',
  },
  step2b: {
    videoId: 'gNS_QjGAs_k',
    timeMinutes: 1,
    thumbnail: 'https://img.youtube.com/vi/gNS_QjGAs_k/maxresdefault.jpg',
    title: 'Step 2B: Tibialis Raise (again)',
    reps: '25 reps',
    notes: 'No break - move directly to next exercise',
    videoTitle: 'Tibialis Raise Demonstration',
    videoDescription: 'Proper tibialis raise technique for shin strength',
  },
  step3: {
    videoId: 'm1aMq9W-jDo',
    timeMinutes: 1,
    thumbnail: 'https://img.youtube.com/vi/m1aMq9W-jDo/maxresdefault.jpg',
    title: 'Step 3: KOT Calf Raise',
    reps: '25 reps',
    notes: 'No break - move directly to next exercise',
    videoTitle: 'KOT Calf Raise with Scaling Options',
    videoDescription: 'KOT calf raise technique with single leg progression',
  },
  step4: {
    videoId: 'enDlOQYjEwI',
    timeMinutes: 2,
    thumbnail: 'https://i.ytimg.com/vi/enDlOQYjEwI/maxresdefault.jpg',
    title: 'Step 4: Patrick Step',
    reps: '25 reps per side',
    notes: 'Get full KOT Calf Raise before progressing here. 1 set minimum, up to 3 sets per side if weak point - no breaks needed.',
    videoTitle: 'Patrick Step-Up Progression',
    videoDescription: 'Patrick > Poliquin > Petersen step-up progression demonstration',
  },
  step5: {
    videoId: 'iUcNxoF-kyo',
    startTime: 0,
    timeMinutes: 4,
    thumbnail: 'https://i.ytimg.com/vi/iUcNxoF-kyo/maxresdefault.jpg',
    title: 'Step 5: ATG Split Squat',
    reps: '5 sets of 5 reps per side',
    notes: 'Get full Patrick Step before progressing here. 30 second breaks between each set.',
    videoTitle: 'ATG Split Squat Demonstration',
    videoDescription: 'Deep range of motion split squat technique',
  },
  step6: {
    videoId: 'bPO5FW54Qz8',
    startTime: 0,
    timeMinutes: 1.5,
    thumbnail: 'https://i.ytimg.com/vi/bPO5FW54Qz8/maxresdefault.jpg',
    title: 'Step 6: Elephant Walk',
    reps: '36 reps per side',
    notes: '',
    videoTitle: 'Elephant Walk Demonstration',
    videoDescription: 'Elephant walk drill for hamstring and hip mobility',
  },
  step7: {
    videoId: 'HSPwnGTWHwQ',
    timeMinutes: 1.5,
    thumbnail: 'https://i.ytimg.com/vi/HSPwnGTWHwQ/maxresdefault.jpg',
    title: 'Step 7: L-Sit',
    reps: '60 seconds',
    notes: '1 set minimum, up to 3 sets, with 1-2 minute breaks, if this is a weak point for you.',
    videoTitle: 'L-Sit Progression Tutorial',
    videoDescription: 'L-sit progression and technique guide',
  },
  step8: {
    videoId: 'Jay0Sd2exg0',
    timeMinutes: 1.5,
    thumbnail: 'https://img.youtube.com/vi/Jay0Sd2exg0/maxresdefault.jpg',
    title: 'Step 8: Couch Stretch',
    reps: '60 seconds per side',
    notes: '1 set minimum, up to 3 sets if this is a weak point for you.',
    videoTitle: 'Couch Stretch Demonstration',
    videoDescription: 'Proper couch stretch technique for hip flexors',
  },
  step9: {
    videoId: '4_-XNRGOIko',
    timeMinutes: 3,
    thumbnail: 'https://i.ytimg.com/vi/4_-XNRGOIko/maxresdefault.jpg',
    title: 'Step 9: Piriformis Stretch',
    reps: '2 sets of 90 seconds per side',
    notes: '',
    videoTitle: 'Piriformis Stretch Demonstration',
    videoDescription: 'Piriformis stretch technique for hip and glute mobility',
  },
};

export const EXERCISE_ORDER = [
  'warmup',
  'step1',
  'step2',
  'step2b',
  'step3',
  'step4',
  'step5',
  'step6',
  'step7',
  'step8',
  'step9',
];
